# Generated by Django 2.2.3 on 2019-12-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0002_auto_20191213_0038'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'verbose_name': 'University', 'verbose_name_plural': 'Universities'},
        ),
    ]
