# Generated by Django 2.2.3 on 2019-12-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0003_auto_20191219_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
