# Generated by Django 2.2.3 on 2019-12-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0004_auto_20191219_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='university',
            name='location',
            field=models.CharField(max_length=150),
        ),
    ]
