# Generated by Django 2.2.3 on 2020-01-07 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0008_auto_20200107_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datetimeslot',
            name='isReserved',
        ),
    ]
