# Generated by Django 2.2.3 on 2020-01-07 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0009_remove_datetimeslot_isreserved'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='desciption',
            new_name='description',
        ),
    ]
