# Generated by Django 2.2.3 on 2019-12-29 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0005_auto_20191219_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='datetimeslot',
            name='begin_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datetimeslot',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datetimeslot',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='datetimeslot',
            unique_together={('date', 'begin_time', 'end_time', 'place')},
        ),
        migrations.RemoveField(
            model_name='datetimeslot',
            name='datetime',
        ),
    ]
