# Generated by Django 2.2.3 on 2020-01-07 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve_app', '0007_auto_20200107_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='slot',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='reserve_app.DateTimeSlot'),
        ),
    ]
